apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: carina.storage.io
  namespace: {{ .Release.Namespace }}
  annotations:
    csiDriver: "{{ .Values.image.carina.tag }}"
{{ include "carina.labels" . | indent 2 }}
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
